
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Vladek (https://sketchfab.com/vladek27)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-living-room-df179eebec234798aa7fbe6c7eaf492a
Title: Low poly living room
*/

import * as THREE from 'three'
import React, { memo, useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeObjectProps } from '../types/shared'

type GLTFResult = GLTF & {
  nodes: {
    Plane_Material_0: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
}

const Room: React.FC<ThreeObjectProps> = ({...props}) => {
  const { nodes, materials } = useGLTF('/models/low_poly_living_room.glb') as GLTFResult
  return (
    <Float floatIntensity={2}>
    <group {...props} dispose={null}>
      <mesh
        // castShadow
        // receiveShadow
        geometry={nodes.Plane_Material_0.geometry}
        material={materials.Material}
        rotation={[-1.5, 0, 2.3]}
        // scale={100}
      />
    </group>
    </Float>
  )
}

useGLTF.preload('/models/low_poly_living_room.glb')

export default memo(Room)