// import * as THREE from 'three'
// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'
// import { GLTF } from 'three-stdlib'

// type GLTFResult = GLTF & {
//   nodes: {
//     Plane_Material_0: THREE.Mesh
//   }
//   materials: {
//     Material: THREE.MeshStandardMaterial
//   }
// }

// export function Desk(props: any) {
//   const { nodes, materials } = useGLTF('/models/lowqRoom/scene.gltf') as any
//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Plane_Material_0.geometry}
//         material={materials.Material}
//         rotation={[-1.5, 0, 2.3]}
//         //scale={30}
//       />
//     </group>
//   )
// }

// useGLTF.preload('/models/lowqRoom/scene.gltf')

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Vladek (https://sketchfab.com/vladek27)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-living-room-df179eebec234798aa7fbe6c7eaf492a
Title: Low poly living room
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane_Material_0: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
}

export function Room(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/low_poly_living_room.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        // castShadow
        // receiveShadow
        geometry={nodes.Plane_Material_0.geometry}
        material={materials.Material}
        rotation={[-1.5, 0, 2.3]}
        // scale={100}
      />
    </group>
  )
}

useGLTF.preload('/models/low_poly_living_room.glb')